name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update --remote --merge
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run build
    - run: yarn test
  deploy:
    name: Deploy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: . ./tools/az-deploy.sh ${{ secrets.GH_WORKFLOW_TOKEN }}


       