name: CI/CD
on:
  push:
    branches:
      - main
      - ft/*
      - hf/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update --remote --merge
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 16
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run build
    - run: yarn test
       